-- Teste transacional: cria somente fixtures efêmeras e termina em ROLLBACK.
-- Executar com papel de manutenção autorizado; não envia e-mails ou senhas.
begin;
do $$
declare v_org uuid; v_owner uuid; v_email text; v_user uuid:=gen_random_uuid(); v_other uuid:=gen_random_uuid(); v_inv uuid; v_prod uuid; v_sale uuid; v_client uuid; v_count int; v_ok bool; v_id uuid;
begin
 select id,owner_user_id into strict v_org,v_owner from organizations where nome='Slow Office';
 select email into v_email from auth.users where id=v_owner;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',v_owner,'email',v_email,'role','authenticated')::text,true);
 insert into auth.users(id,email,email_confirmed_at,raw_user_meta_data,raw_app_meta_data) values(v_user,'qa-caixa-fluxo@nexo.invalid',now(),'{}','{}');
 insert into auth.users(id,email,email_confirmed_at,raw_user_meta_data,raw_app_meta_data) values(v_other,'qa-outro-fluxo@nexo.invalid',now(),'{}','{}');
 execute 'set local role authenticated';
 v_inv:=public.criar_convite_equipe('QA-CAIXA-FLUXO@nexo.invalid','caixa');
 if public.criar_convite_equipe('qa-caixa-fluxo@nexo.invalid','caixa')<>v_inv then raise exception 'Convite duplicado'; end if;
 insert into public.produtos(nome,preco,custo,estoque,status,tem_variacoes) values('QA Caixa transitório',100,0,4,'ativo',false) returning id into v_prod;
 execute 'reset role';
 perform set_config('request.jwt.claims',jsonb_build_object('sub',v_other,'email','qa-outro-fluxo@nexo.invalid','role','authenticated')::text,true);
 execute 'set local role authenticated';
 v_ok:=false; begin perform public.aceitar_convite_equipe(v_inv); exception when others then v_ok:=true; end;
 if not v_ok then raise exception 'Outro e-mail aceitou convite'; end if;
 execute 'reset role';
 perform set_config('request.jwt.claims',jsonb_build_object('sub',v_user,'email','qa-caixa-fluxo@nexo.invalid','role','authenticated')::text,true);
 execute 'set local role authenticated';
 execute 'reset role';
 update auth.users set email_confirmed_at=null where id=v_user;
 execute 'set local role authenticated';
 v_ok:=false; begin perform public.aceitar_convite_equipe(v_inv); exception when others then v_ok:=true; end;
 if not v_ok then raise exception 'E-mail não confirmado entrou'; end if;
 execute 'reset role';
 update auth.users set email_confirmed_at=now() where id=v_user;
 update public.organization_invites set expires_at=now()-interval '1 day' where id=v_inv;
 execute 'set local role authenticated';
 v_ok:=false; begin perform public.aceitar_convite_equipe(v_inv); exception when others then v_ok:=true; end;
 if not v_ok then raise exception 'Convite expirado entrou'; end if;
 execute 'reset role';
 update public.organization_invites set expires_at=now()+interval '7 days',status='revogado' where id=v_inv;
 execute 'set local role authenticated';
 v_ok:=false; begin perform public.aceitar_convite_equipe(v_inv); exception when others then v_ok:=true; end;
 if not v_ok then raise exception 'Convite revogado entrou'; end if;
 execute 'reset role';
 update public.organization_invites set status='pendente' where id=v_inv;
 execute 'set local role authenticated';
 if public.aceitar_convite_equipe(v_inv)<>v_org then raise exception 'Aceite entrou na organização errada'; end if;
 if public.aceitar_convite_equipe(v_inv)<>v_org then raise exception 'Aceite não idempotente'; end if;
 if public.current_papel()<>'caixa' then raise exception 'Papel incorreto'; end if;
 if (select count(*) from organization_members)<>1 then raise exception 'Caixa vê identidades da equipe'; end if;
 if (select count(*) from vendas)<>0 then raise exception 'Caixa vê histórico de outros'; end if;
 if (select count(*) from despesas)>0 or (select count(*) from funcionarios)>0 or (select count(*) from fechamentos_financeiros)>0 then raise exception 'Caixa vê gestão financeira'; end if;
 select id into v_client from public.cadastrar_cliente_caixa('QA Cliente transitório','32999998888');
 v_ok:=false; begin perform public.cadastrar_cliente_caixa('QA Cliente transitório','32999998888'); exception when others then v_ok:=true; end;
 if not v_ok then raise exception 'Cliente duplicado'; end if;
 v_sale:=public.criar_venda(v_client,'Não informado',null,'dinheiro',1,0,100,0,null,jsonb_build_array(jsonb_build_object('produto_id',v_prod,'quantidade',1,'preco_unitario',100)),null,null,null,null,'qa-caixa-venda-transitoria');
 if public.criar_venda(v_client,'Não informado',null,'dinheiro',1,0,100,0,null,jsonb_build_array(jsonb_build_object('produto_id',v_prod,'quantidade',1,'preco_unitario',100)),null,null,null,null,'qa-caixa-venda-transitoria')<>v_sale then raise exception 'Venda duplicada'; end if;
 perform public.definir_data_venda(v_sale,'2026-09-29');
 if (select data_venda from vendas where id=v_sale)<>'2026-09-29'::date then raise exception 'Venda retroativa não salva'; end if;
 if (select estoque from produtos where id=v_prod)<>3 then raise exception 'Baixa incorreta'; end if;
 v_ok:=false; begin perform public.registrar_movimentacao(v_prod,'ajuste_positivo',1,'QA',null,null,null,'qa-ajuste-negado'); exception when others then v_ok:=true; end;
 if not v_ok then raise exception 'Caixa ajustou estoque fora de uma venda'; end if;
 v_ok:=false; begin perform public.cancelar_venda(v_sale,'QA cancelamento negado'); exception when others then v_ok:=true; end;
 if not v_ok then raise exception 'Caixa cancelou venda'; end if;
 v_ok:=false; begin perform public.criar_convite_equipe('qa-intruso@nexo.invalid','gerente'); exception when others then v_ok:=true; end;
 if not v_ok then raise exception 'Caixa convidou membro'; end if;
 delete from public.vendas where id=v_sale;
 if not exists(select 1 from vendas where id=v_sale) then raise exception 'Caixa excluiu venda'; end if;
 v_id:=public.criar_venda_multiforma(null,'Não informado',null,0,null,jsonb_build_array(jsonb_build_object('produto_id',v_prod,'quantidade',1,'preco_unitario',100)),jsonb_build_array(jsonb_build_object('forma','dinheiro','valor',50),jsonb_build_object('forma','pix','valor',50)),'qa-caixa-multiforma-transitoria');
 if (select count(*) from venda_pagamentos where venda_id=v_id)<>2 then raise exception 'Pagamento dividido não funciona'; end if;
 v_id:=public.criar_venda(v_client,'Não informado',null,'promissoria',1,0,null,0,null,jsonb_build_array(jsonb_build_object('produto_id',v_prod,'quantidade',1,'preco_unitario',100)),1,'2026-10-15',null,null,'qa-caixa-promissoria-transitoria');
 if not exists(select 1 from promissorias where venda_id=v_id) then raise exception 'Promissória da venda não criada'; end if;
 execute 'reset role';
 perform set_config('request.jwt.claims',jsonb_build_object('sub',v_owner,'email',v_email,'role','authenticated')::text,true);
 update public.vendas set registrado_em=now()-interval '1 second' where id=v_sale;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',v_user,'email','qa-caixa-fluxo@nexo.invalid','role','authenticated')::text,true);
 execute 'set local role authenticated';
 v_ok:=false; begin update public.vendas set total=1 where id=v_sale; exception when others then v_ok:=true; end;
 if not v_ok then raise exception 'Caixa alterou valor após registro'; end if;
 update public.produtos set preco=1 where id=v_prod;
 if (select preco from public.produtos where id=v_prod)<>100 then raise exception 'Caixa alterou catálogo'; end if;
 if exists(select 1 from public.produtos where organization_id<>v_org) then raise exception 'Caixa vê catálogo de outra loja'; end if;
 if has_function_privilege('anon','public.aceitar_convite_equipe(uuid)','execute') then raise exception 'Anônimo pode aceitar convite'; end if;
 execute 'reset role';
 perform set_config('request.jwt.claims',jsonb_build_object('sub',v_owner,'email',v_email,'role','authenticated')::text,true);
 execute 'set local role authenticated';
 if not exists(select 1 from vendas where id=v_sale and organization_id=v_org) then raise exception 'Venda do caixa não chegou à loja'; end if;
 if (select estoque from produtos where id=v_prod)<>1 then raise exception 'Saldo final incorreto'; end if;
 execute 'reset role';
 raise notice 'OK: convite, e-mail, aceite idempotente, cliente, vendas simples/dividida/fiado, data retroativa, estoque e gestão isolada';
end $$;
select 'OK: convite seguro, isolamento, vendas e estoque; fixtures descartadas por rollback' as resultado;
rollback;
